--DDL - LINGUAGEM DE CRIAÇÃO DE DADOS

--CRIA BANCO DE DADOS DO PROGRAMA FEITO PARA SENATUR
--Atividade do curso de Desenvolvimento de Sistemas - Senai Informática

CREATE DATABASE SENATUR_TARDE

USE SENATUR_TARDE

--Criar uma tabela de pacotes com os campos PacoteId, NomePacote, Descricao, DataIda, DataVolta, Valor, Ativo e NomeCidade;

CREATE TABLE PACOTES (
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	PACOTE_ID INT IDENTITY PRIMARY KEY
	,NOME_PACOTE VARCHAR(200)NOT NULL UNIQUE
	,DESCRICAO VARCHAR(1000)NOT NULL UNIQUE
	,DATA_IDA DATE NOT NULL UNIQUE	
	,DATA_VOLTA DATE NOT NULL UNIQUE
	,VALOR MONEY NOT NULL	
	,ATIVO BIT NOT NULL
	,NOME_CIDADE  VARCHAR(200)NOT NULL UNIQUE
	);

--Criar uma tabela de usuários contendo os campos de UsuarioId, Email, Senha e TipoUsuario;
CREATE TABLE USUARIOS(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	USUARIO_ID INT IDENTITY PRIMARY KEY,
	Email VARCHAR(150) NOT NULL,
	Senha  VARCHAR(150) NOT NULL,
	TipoUsuario BIT NOT NULL
);
